# Generated by Django 5.1 on 2024-08-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plane',
            name='image',
        ),
    ]
