# Generated by Django 5.1 on 2024-08-23 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_plane_image_sighting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
