# Generated by Django 5.1 on 2024-08-25 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_sighting_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sighting',
            options={'ordering': ['-datetime']},
        ),
        migrations.AlterField(
            model_name='sighting',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sighting date'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='registration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
