# Generated by Django 5.1 on 2024-08-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_plane_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='category',
            field=models.CharField(choices=[('GA', 'General Aviation'), ('MI', 'Military'), ('PR', 'Private'), ('CP', 'Corporite'), ('AG', 'Agricultural'), ('SP', 'Sport'), ('DR', 'Drone'), ('GL', 'Glider')], default='GA', max_length=2),
        ),
    ]
