# Generated by Django 5.1 on 2024-08-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_plane_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
